title:            VS Blog
description:      personal blog about cloud-fun

# put your disqus here
disqus_shortname: valentinsavenko-github-io
comments: true
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 90
logo:             images/Cloud-icon.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://valentinsavenko.de

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  # - title: 'Tags'
  #   url: '/tags'
  # - title: 'About'
    # url: '/about'
  # - title: 'Favorites'
  #   url: '#'
  #   submenu:
  #     - title: 'Code Highlighter'
  #       url: '/intro/code-highlighting-post/'
  #     - title: 'Sample Post'
  #       url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Valentin Savenko
  site:           http://valentinsavenko.de/about
  avatar:         images/vs.jpg
  bio:            "Automation Engineer @ Signavio"
  email:          vale-save@t-online.de
about:
  Software Engineering consists of using and understanding a whole set of software and code-snippets of other developers.
  Often how-to tutorials just start with an empty canvas and showcase something that is easy enough to be solved in a single context.
  IT Systems are more complicated than that. We often have to google for snippets of code and glue them together.
  The challenge there is to get just enough context to be able to understand and possibly, improve, on the work of people.
  I try to showcase this for non-trivial tasks I encountered and explain not only the solution, but also the context of the problem space as good as I can!


# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/valentinsavenko"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/valentin-savenko-61b38797"
  - title: "product-hunt"
    url: "https://forge.puppet.com/valentinsavenko"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-132765615-1
google_verify: http://sites.google.com/site/neonapevvs/
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
