title:            VS Blog
description:      personal blog about cloud-fun

# put your disqus here
disqus_shortname: valentinsavenko-github-io
comments: true
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 90
logo:             images/Cloud-icon.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://valentinsavenko.de

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  # - title: 'Tags'
  #   url: '/tags'
  # - title: 'About'
    # url: '/about'
  # - title: 'Favorites'
  #   url: '#'
  #   submenu:
  #     - title: 'Code Highlighter'
  #       url: '/intro/code-highlighting-post/'
  #     - title: 'Sample Post'
  #       url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Valentin Savenko
  site:           http://valentinsavenko.de/about
  avatar:         images/vs.jpg
  bio:            "System Engineer with focus on automation"
  email:          vale-save@t-online.de
about_author: Interested in I studied mostly Software Engineering methodology for biological applications, but have since moved on to solve technological challenges in the web.
  I dabbled in test automation with Selenium for an e-commerce website but quickly noticed that the actual fun part was the automation.
  I don't like doing the same manual task more than twice. Therefore I started getting into deployment pipelines and the DevOps ideology. After building the deployment system for the Java app at my previous company and automate most of the QA work that I was hired for, I switched to System Engineering at Netcentric.
  Here I learned much more about Linux and networks and administering complex Java applications.
  During the last year and a half, I moved projects and am now mostly focused on provisioning Infrastructure as Code with CloudFormation Templates on AWS and configure those server compositions with Puppet. Most of those steps are automated, documented and fun to use.

  I would like the opportunity to learn more about different setups and maybe get experience (in production) with containerization and distributed systems.

  The team setup is important to me and I'll have a lot of questions on that topic!

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/valentinsavenko"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/valentin-savenko-61b38797"
  - title: "product-hunt"
    url: "https://forge.puppet.com/valentinsavenko"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-132765615-1
google_verify: http://sites.google.com/site/neonapevvs/
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
